<?php

// Quelle: https://de.wikipedia.org/wiki/Kategorie:Vertreter_einer_Verschw%C3%B6rungstheorie
$leute = array(
"Gary Allen",
"Martin Allen",
"Ernesto Araúj",
"François Asselinea",
"Shiva Ayyadurai",
"Hartmut Bachmann",
"Michael Baigent",
"Die Bandbreite",
"Bruno Bandulet",
"Augustin Barruel",
"Adam Bartoš",
"Greta Berlin",
"Eugene Bird",
"Peter Boehringer",
"Jair Bolsonaro",
"Jakow Alexandrowitsch Brafman",
"Eddie Bravo",
"Mathias Bröckers",
"Madeleine Duncan Brown",
"William Joseph Bryan",
"Andreas von Bülow",
"J. G. Burg",
"Rashid Buttar",
"William Guy Carr",
"Olavo de Carvalho",
"Christian-Identity-Bewegung",
"Jo Conrad",
"Milton William Cooper",
"Cabo Daciolo",
"Ruediger Dahlke",
"David Dees",
"Christina von Dreien",
"Peter Duesberg",
"Cecil Egwuatu",
"Elias Davidsson",
"Jürgen Elsässer",
"F. William Engdahl",
"Stefan Erdmann",
"Viktor Farkas",
"Teresa Forcades i Vila",
"Daniele Ganser",
"Joseph Heinrich Garnier",
"Wolfgang Gedeon",
"Ernst August Anton von Göchhausen",
"Henri Roger Gougenot des Mousseaux",
"David Ray Griffin",
"G. Edward Griffin",
"John Hagee",
"Ryke Geerd Hamer",
"Karl Heise",
"Eva Herman",
"Attila Hildmann",
"Jan Udo Holey",
"Stefan Homburg",
"Der Honigmann",
"Andreas Hönisch",
"Christoph Hörstel",
"David Icke",
"Oliver Janich",
"Ken Jebsen",
"Alex Jones",
"Steven Jones",
"Peter Joseph",
"Bill Kaysing",
"Robert Francis Kennedy junior",
"Kilez More",
"Jennifer Klauninger",
"Bernd Klein",
"Adolph Knigge",
"Karl Koch",
"Kollegah",
"Fehmi Koru",
"Wilhelm Landig",
"David Eden Lane",
"Stefan Lanka",
"Lyndon LaRouche",
"Robert Lazar",
"Michael Lebron",
"Erich Ludendorff",
"Mathilde Ludendorff",
"Nikolai Jewgenjewitsch Markow",
"Wilhelm Marr",
"Jim Marrs",
"Robert Jay Mathews",
"Massimo Mazzucco",
"Joseph McCarthy",
"Gottfried Melzer",
"Thierry Meyssan",
"Ludwig Müller von Hausen",
"Dirk Mülle",
"Eustace Mullins",
"Xavier Naidoo",
"Andrew Napolitano",
"Nikolai Nerling",
"Sergei Alexandrowitsch Nilus",
"Titus Oates",
"Ralf Otterpohl",
"Patriot Movement",
"Everaldo Pereira",
"Pierre Plantard",
"Ergün Poyraz",
"Robert Prantner",
"Sayyid Qutb",
"Emil Rahm",
"Gerhoch Reisegger",
"Andreas von Rétyi",
"Armin Risi",
"Mario Rönsch",
"Olaf Rose",
"Alfred Roth",
"Johannes Rothkranz",
"Robin de Ruiter",
"Ivo Sasek",
"Wladimir Wolfowitsch Schirinowski",
"Thorsten Schulte",
"Jakob Segal",
"W. Cleon Skousen",
"René Sonderegger",
"Ewald Stadler",
"Johann August von Starck",
"Axel Stoll",
"Brenton Tarrant",
"Inge M. Thürkauf",
"Donald Trump",
"Udo Ulfkotte",
"Walter Veith",
"Michael Vogt",
"C. Peter Wagner",
"Paul Joseph Watson",
"Nesta Webster",
"Michael Wendler",
"Gerhard Wisnewski",
"Harun Yahya",
"Helga Zepp-LaRouche",
);

$randleute=array_rand($leute, 3);

echo $leute[$randleute[0]]." vergleicht ".$leute[$randleute[1]]." mit ".$leute[$randleute[2]];

?>
